--CREATE DATABASE QLTHUVIEN

GO
--TAI KHOAN
CREATE TABLE CHUCVU
(
	MACHUCVU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENCHUCVU NVARCHAR(50),
)
GO
--NHAN VIEN
CREATE TABLE NHANVIEN
(
	MANHANVIEN INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDANGNHAP VARCHAR(20),
	MATKHAU VARCHAR(50),
	TENNHANVIEN NVARCHAR(100),
	CMND VARCHAR(12),
	NGAYSINH DATE,
	SODIENTHOAI VARCHAR(10),
	DIACHI NVARCHAR(100),
	MACHUCVU INT,
	TRANGTHAI BIT
	FOREIGN KEY (MACHUCVU) REFERENCES CHUCVU(MACHUCVU)
)
GO
--DANH MUC
CREATE TABLE DANHMUC
(
	MADANHMUC INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDANHMUC NVARCHAR(50),
)
GO
--NHAXUATBAN
CREATE TABLE NHAXUATBAN
(
	MANHAXUATBAN INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENNHAXUATBAN NVARCHAR(50),
)
GO
--VITRI
CREATE TABLE VITRI
(
	MAVITRI INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENVITRI NVARCHAR(50),
)
GO
--TACGIA
CREATE TABLE TACGIA
(
	MATACGIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENTACGIA NVARCHAR(50),
)
GO
--TRANG THAI 1: HET HAN/BI KHOA ,0: BINH THUONG
--DOCGIA
CREATE TABLE DOCGIA
(
	MADOCGIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDOCGIA NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	NGHENGHIEP NVARCHAR(50),
	SOCMND VARCHAR(10),
	NGAYCAPTHE DATE,
	NGAYHETHAN DATE,
	SOLUONGSACHDUOCMUON INT,
	TIENKIGUI MONEY,
	TRANGTHAI BIT
)
GO

--SACH
CREATE TABLE SACH
(
	MASACH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENSACH NVARCHAR(250),
	MADANHMUC INT,
	MATACGIA INT,
	MANHAXUATBAN INT,
	SOLUONGSACHCON INT,
	MAVITRI INT,
	GIAGOC MONEY
	FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC),
	FOREIGN KEY (MATACGIA) REFERENCES TACGIA(MATACGIA),
	FOREIGN KEY (MANHAXUATBAN) REFERENCES NHAXUATBAN(MANHAXUATBAN),
	FOREIGN KEY (MAVITRI) REFERENCES VITRI(MAVITRI)
)
GO

--TRANG THAI 1: QUA HAN ,0: CHUA QUA HAN
--PHIEUYEUCAU
CREATE TABLE PHIEUYEUCAU
(
	SOPHIEU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MADOCGIA INT,
	MASACH INT,
	SOLUONGMUON INT,
	NGAYMUON DATE,
	NGAYTRA DATE,
	MANHANVIEN INT,
	TRANGTHAI BIT,
	FOREIGN KEY (MADOCGIA) REFERENCES DOCGIA(MADOCGIA),
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)
GO

 /*TẠO VIEW CHO SACH QUA HAN */
 CREATE VIEW SACH_QUA_HAN 
 AS
 SELECT D.MADOCGIA, D.TENDOCGIA, S.TENSACH, P.SOLUONGMUON, P.NGAYMUON, P.NGAYTRA,P.MANHANVIEN,N.TENNHANVIEN , P.TRANGTHAI
 FROM DOCGIA D, SACH S, PHIEUYEUCAU P, NHANVIEN N
 WHERE P.MANHANVIEN=N.MANHANVIEN AND D.MADOCGIA=P.MADOCGIA AND P.MASACH=S.MASACH AND P.TRANGTHAI='TRUE'

  /*TẠO VIEW CHO SACH ĐANG MƯỢN */
 CREATE VIEW SACH_DANG_MUON
 AS
 SELECT P.MASACH, S.TENSACH, SUM(P.SOLUONGMUON) AS SOLUONG
 FROM PHIEUYEUCAU P, SACH S
 WHERE P.MASACH=S.MASACH
 GROUP BY P.MASACH, S.TENSACH